//! Localization framework for fixed index/footer chrome strings.
//!
//! Provides a [`Locale`] enum and a [`ChromeStrings`] struct so the tutorial
//! renderer can emit localized headings/labels without touching generated
//! content. Adding a new locale is one match arm in [`Locale::parse`] /
//! [`Locale::as_str`] plus one struct initializer in
//! [`ChromeStrings::for_locale`].
//!
//! See `docs/best-practices.md` §13 for the Mermaid-no-accents rule —
//! [`ChromeStrings::chapters_heading`] uses the accent-free "Capitulos" so it
//! is safe inside Mermaid labels.

use serde::{Deserialize, Serialize};
use std::fmt;

/// Supported UI locale.
///
/// Wire format is the lowercase ISO-ish code (`"en"`, `"es"`) via
/// `#[serde(rename_all = "lowercase")]`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Locale {
    /// English.
    En,
    /// Spanish.
    Es,
}

impl Locale {
    /// Canonical wire string (`"en"` or `"es"`).
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::En => "en",
            Self::Es => "es",
        }
    }

    /// Parse a locale code case-insensitively.
    ///
    /// Returns `None` for unrecognized input; callers should fall back to
    /// [`Locale::En`] (see [`Locale::parse_or_default`]).
    #[must_use]
    pub fn parse(s: &str) -> Option<Self> {
        match s.to_ascii_lowercase().as_str() {
            "en" => Some(Self::En),
            "es" => Some(Self::Es),
            _ => None,
        }
    }

    /// Parse a locale code, falling back to English when unknown.
    ///
    /// Convenience for renderers that never want to deal with `None`.
    #[must_use]
    pub fn parse_or_default(s: &str) -> Self {
        Self::parse(s).unwrap_or(Self::En)
    }
}

impl fmt::Display for Locale {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Fixed chrome strings (headings, labels, footer) for one [`Locale`].
///
/// All fields are `&'static str` so the struct is `Copy` and cheap to pass
/// around. Generated content (chapter titles, file paths, code identifiers)
/// is never localized — only these fixed chrome strings.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ChromeStrings {
    /// "Chapters" / "Capitulos" (accent-free for Mermaid safety).
    pub chapters_heading: &'static str,
    /// "Setup Guide" / "Guía de Configuración".
    pub setup_link: &'static str,
    /// "Architecture Overview" / "Vista General de Arquitectura".
    pub overview_link: &'static str,
    /// "Evidence" / "Evidencia".
    pub evidence_label: &'static str,
    /// "Key Files" / "Archivos Clave".
    pub key_files_label: &'static str,
    /// "Learning Path" / "Ruta de Aprendizaje".
    pub learning_path_heading: &'static str,
    /// "System Map" / "Mapa del Sistema".
    pub system_map_heading: &'static str,
    /// "Core Concepts" / "Conceptos Centrales".
    pub concept_map_heading: &'static str,
    /// "How to Use This Tutorial" / "Cómo Usar Este Tutorial".
    pub how_to_use_heading: &'static str,
    /// "Generated by brigid" / "Generado por brigid".
    pub attribution: &'static str,
}

impl ChromeStrings {
    /// Return the chrome strings for the given [`Locale`].
    ///
    /// Adding a new locale = one match arm here with a fresh struct
    /// initializer.
    #[must_use]
    pub fn for_locale(locale: Locale) -> Self {
        match locale {
            Locale::En => Self {
                chapters_heading: "Chapters",
                setup_link: "Setup Guide",
                overview_link: "Architecture Overview",
                evidence_label: "Evidence",
                key_files_label: "Key Files",
                learning_path_heading: "Learning Path",
                system_map_heading: "System Map",
                concept_map_heading: "Core Concepts",
                how_to_use_heading: "How to Use This Tutorial",
                attribution: "Generated by brigid",
            },
            Locale::Es => Self {
                chapters_heading: "Capitulos",
                setup_link: "Guía de Configuración",
                overview_link: "Vista General de Arquitectura",
                evidence_label: "Evidencia",
                key_files_label: "Archivos Clave",
                learning_path_heading: "Ruta de Aprendizaje",
                system_map_heading: "Mapa del Sistema",
                concept_map_heading: "Conceptos Centrales",
                how_to_use_heading: "Cómo Usar Este Tutorial",
                attribution: "Generado por brigid",
            },
        }
    }

    /// English chrome strings (the canonical fallback).
    #[must_use]
    pub fn english() -> Self {
        Self::for_locale(Locale::En)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn locale_as_str_round_trips_en() {
        let json = serde_json::to_string(&Locale::En).expect("serialize en");
        assert_eq!(json, "\"en\"");
        let back: Locale = serde_json::from_str(&json).expect("deserialize en");
        assert_eq!(back, Locale::En);
    }

    #[test]
    fn locale_as_str_round_trips_es() {
        let json = serde_json::to_string(&Locale::Es).expect("serialize es");
        assert_eq!(json, "\"es\"");
        let back: Locale = serde_json::from_str(&json).expect("deserialize es");
        assert_eq!(back, Locale::Es);
    }

    #[test]
    fn locale_parse_valid() {
        assert_eq!(Locale::parse("en"), Some(Locale::En));
        assert_eq!(Locale::parse("es"), Some(Locale::Es));
    }

    #[test]
    fn locale_parse_case_insensitive() {
        assert_eq!(Locale::parse("EN"), Some(Locale::En));
        assert_eq!(Locale::parse("ES"), Some(Locale::Es));
        assert_eq!(Locale::parse("En"), Some(Locale::En));
        assert_eq!(Locale::parse("Es"), Some(Locale::Es));
    }

    #[test]
    fn locale_parse_invalid_returns_none() {
        assert_eq!(Locale::parse("fr"), None);
        assert_eq!(Locale::parse(""), None);
        assert_eq!(Locale::parse("english"), None);
    }

    #[test]
    fn locale_display_matches_as_str() {
        assert_eq!(Locale::En.to_string(), "en");
        assert_eq!(Locale::Es.to_string(), "es");
    }

    #[test]
    fn unknown_locale_falls_back_to_english() {
        let locale = Locale::parse("fr").unwrap_or(Locale::En);
        assert_eq!(locale, Locale::En);
        assert_eq!(Locale::parse_or_default("fr"), Locale::En);
        assert_eq!(Locale::parse_or_default("xyz"), Locale::En);
    }

    #[test]
    fn chrome_strings_english_all_fields() {
        let s = ChromeStrings::for_locale(Locale::En);
        assert_eq!(s.chapters_heading, "Chapters");
        assert_eq!(s.setup_link, "Setup Guide");
        assert_eq!(s.overview_link, "Architecture Overview");
        assert_eq!(s.evidence_label, "Evidence");
        assert_eq!(s.key_files_label, "Key Files");
        assert_eq!(s.learning_path_heading, "Learning Path");
        assert_eq!(s.system_map_heading, "System Map");
        assert_eq!(s.concept_map_heading, "Core Concepts");
        assert_eq!(s.how_to_use_heading, "How to Use This Tutorial");
        assert_eq!(s.attribution, "Generated by brigid");
    }

    #[test]
    fn chrome_strings_spanish_all_fields() {
        let s = ChromeStrings::for_locale(Locale::Es);
        assert_eq!(s.chapters_heading, "Capitulos");
        assert_eq!(s.setup_link, "Guía de Configuración");
        assert_eq!(s.overview_link, "Vista General de Arquitectura");
        assert_eq!(s.evidence_label, "Evidencia");
        assert_eq!(s.key_files_label, "Archivos Clave");
        assert_eq!(s.learning_path_heading, "Ruta de Aprendizaje");
        assert_eq!(s.system_map_heading, "Mapa del Sistema");
        assert_eq!(s.concept_map_heading, "Conceptos Centrales");
        assert_eq!(s.how_to_use_heading, "Cómo Usar Este Tutorial");
        assert_eq!(s.attribution, "Generado por brigid");
    }

    #[test]
    fn chrome_strings_english_helper_matches_for_locale() {
        assert_eq!(
            ChromeStrings::english(),
            ChromeStrings::for_locale(Locale::En)
        );
    }
}
